ZERO = 0
ONE_BYTE = 2**8
TWO_BYTES = ONE_BYTE * 2
FOUR_BYTES = ONE_BYTE * 4

DOT = "."
COLON = ":"

ASN_MAX = FOUR_BYTES - 1
VID_MAX = 2**12 - 1

IPV4_OCTET_MAX = ONE_BYTE - 1
IPV4_MAX = FOUR_BYTES - 1
