ZERO = 0
ONE_BYTE = 2**8
TWO_BYTES = ONE_BYTE**2
FOUR_BYTES = TWO_BYTES**2

DOT = "."
COLON = ":"
SLASH = "/"

ASN_MAX = FOUR_BYTES - 1

DEFAULT_VID = 1
VID_MAX = 2**12 - 1

IPV4_PREFIXLEN_MAX = 32
IPV4_MAX = FOUR_BYTES - 1
IPV4_OCTET_MAX = ONE_BYTE - 1
